'use strict';
module.exports = {
  credentials: 
  {
    //get apiKey 
    "apiKey": "IYN0AAN1CZGQWDGA7KIO215e5XG1tb52rFbG0jkPEP1smdW90",
    "sharedSecret": "es+k+PVj/je3oEu{66Q8E/HypY+3#MGO3hlkzMxX",
    //Call id needs to be generated by clicking on Visa Checkout button
    "checkoutCallId" : "6046589837988198001",
    "visaUrl": "https://sandbox.api.visa.com/"
  }
}
