# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'merchant-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for merchant-app
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
